### ISSUE TITLE
getIcingaDirectorVersion Error

### ISSUE THREAD

**Issue by vittel1** [LordHepipud/icinga2-powershell-module#50] opened 2017-07-28 07:35 UTC
Hi,

at the moment I test the newest version of the powershell module. At lot of changes...

I call it like this:

```
$icinga = Icinga2AgentModule `
    -FetchAgentFQDN       $TRUE `
    -DirectorUrl          'https://icinga-master/icingaweb2/director/' `
    -DirectorUser         'ticketuser' `
    -DirectorPassword     'password' `
    -ParentZone      'master' `
    -ParentEndpoints 'icinga-master' -EndpointsConfig 'icinga-master;5665'`
    -CAServer        'icinga-master'

exit $icinga.installMonitoringComponents();
```

And I get this error:

> Exception calling "getIcingaDirectorVersion" with "0" argument(s): "Exception calling "createHTTPRequest" with "6" argument(s): "Cannot convert null to type "System.Net.HttpSta
> tusCode" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "Continue, SwitchingPr
> otocols, OK, Created, Accepted, NonAuthoritativeInformation, NoContent, ResetContent, PartialContent, MultipleChoices, Ambiguous, MovedPermanently, Moved, Found, Redirect, SeeO
> ther, RedirectMethod, NotModified, UseProxy, Unused, TemporaryRedirect, RedirectKeepVerb, BadRequest, Unauthorized, PaymentRequired, Forbidden, NotFound, MethodNotAllowed, NotA
> cceptable, ProxyAuthenticationRequired, RequestTimeout, Conflict, Gone, LengthRequired, PreconditionFailed, RequestEntityTooLarge, RequestUriTooLong, UnsupportedMediaType, Requ
> estedRangeNotSatisfiable, ExpectationFailed, UpgradeRequired, InternalServerError, NotImplemented, BadGateway, ServiceUnavailable, GatewayTimeout, HttpVersionNotSupported".""

Do you have any idea why this happens?
PsVersion 4 on a Windows 7

**Comment by LordHepipud** [comment] 2017-07-28 08:31
Hello,

thank you for the report. Which version of the Icinga Director are you using?

Configuration -> Modules -> Director

Are you using a taged version or the current master of the Director?

Is the version of the module from the master or the next branch?

Thank you in advance!

**Comment by vittel1** [comment] 2017-07-28 08:49
Configuration -> Modules -> Director:
Version : 1.3.1
Git Commit : 75ca51e85b4823f79564248ef7ef01c448b374f9

I not fully understand the other two questions. Don't know exactly how to find out..(sorry)
Installed the director yesterday at 1pm

> git clone https://github.com/Icinga/icingaweb2-module-director.git director

If you need more information, just tell me how to find out! Thanks!

**Comment by LordHepipud** [comment] 2017-07-28 11:28
Thank you. Yes the second question wasn't that clear :D

Are you using the PowerShell Module from the master or the next branch?

**Comment by vittel1** [comment] 2017-07-28 11:39
The Module from the master :-)

**Comment by LordHepipud** [comment] 2017-07-28 11:43
I'm right now not able to re-produce this issue, but I have an idea.

Could you please try the following:

Search for

```powershell
$exceptionMessage = $_.Exception.Response;
$httpErrorCode = [int][system.net.httpstatuscode]$exceptionMessage.StatusCode;
return $httpErrorCode;
```

and replace it for

```powershell
$exceptionMessage = $_.Exception.Response;
if ($exceptionMessage.StatusCode) {
    return [int][System.Net.HttpStatusCode]$exceptionMessage.StatusCode;
 } else {
    return 900;
}
```

In case the StatusCode is not set for some weird reason, the script should then return a 900 error. If this resolve the issue I will create a proper patch for it.

**Comment by vittel1** [comment] 2017-07-28 11:53
Seems that it helps but now I get this error:

> Exception calling "fetchTicketFromIcingaDirector" with "0" argument(s): "Exception calling "createHTTPRequest" with "6" argument(s): "Exception calling "readResponseStream" wit
> h "1" argument(s): "You cannot call a method on a null-valued expression."""

**Comment by LordHepipud** [comment] 2017-07-28 12:11
Somehow I have a feeling that you are not able to connect property to the Icinga Director.

Can you please search this function

```powershell
$installer | Add-Member -membertype ScriptMethod -name 'readResponseStream' -value {
```

and replace it entirely with

```powershell
$installer | Add-Member -membertype ScriptMethod -name 'readResponseStream' -value {
    param([System.Object]$response);

    if ($response) {
        $responseStream = $response.getResponseStream();
        $streamReader = New-Object IO.StreamReader($responseStream);
        $result = $streamReader.ReadToEnd();
        $response.close()
        $streamReader.close()

        return $result;
    }

    $this.error('Could not retreive response from remote server. Response is null');
    return 'No response from remote server';
}
```

**Comment by vittel1** [comment] 2017-07-28 12:30
I guess you are right. Output know:
(DNS-Lookup Error is an error because of our infrastructure, you can disregard that)

> Warning: You seem to use an older Version of the Icinga Director, as no API version could be retreived.
> Notice: Setting internal Agent Name to icinga-client
> Notice: Trying to fetch Host IP-Address for hostname: icinga-client
> Error: Failed to lookup IP-Address with DNS-Lookup for icinga-client: Exception calling "GetHostEntry" with "1" argument(s): "The requested name is valid, but no data of the reques
> ted type was found"
> Error: Could not retreive response from remote server. Response is null
> Error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
> Error: No response from remote server
> Error: Failed to fetch Ticket from Icinga Director. Error response 900

But the module works if I use this call (maybe this is interessting):

```
    -AgentName        'icinga-client' `
    -Ticket           '576ec8485576831017f633db5925e' `
    -ParentZone      'master' `
    -ParentEndpoints 'icinga-master' -EndpointsConfig 'icinga-master;5665'`
    -CAServer        'icinga-master'
```

**Comment by LordHepipud** [comment] 2017-07-28 13:47
Atleast the script is now no longer throwing unexpected exceptions. I will patch this within the 'next' branch this weekend to ensure this is not causing any else problems. The more interesting part is this:

> Error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

It looks like a SSL related problem. Is the SSL certificate for the Icinga Web server valid? If not this could explain be problem, because if it is not valid, the request is rejected. What happens if you try to access the Director URL from this specific windows host with the web browser? Do you receive a SSL warning or can you simply access the Icinga Web 2 without problems?

If this is a SSL related problem, a argument allowing to skip SSL errors could be a solution to prevent this from happening.

The reason for the last call to work properly is that there is no communication with the Director, just the Icinga 2 servers and the CA server over a secured protocoll which is not causing any SSL error, as otherwise the Icinga 2 infrastructure wouldn't wokr as well.

**Comment by LordHepipud** [comment] 2017-07-28 13:58
You could try the following:

Below

```powershell
$httpRequest.TimeOut = 6000;
```

add

```powershell
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
```

Is this resolving the issue? In case it is a new argument like 

> -IgnoreSSLErrors

could resolve the entire issue.

**Comment by vittel1** [comment] 2017-07-28 14:33
> Is the SSL certificate for the Icinga Web server valid?

Yes...I have forgotten that. My cert is self signed. 

`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }`
I added this part and now it is working :-)

Thank you for the quick help! You did a good job here with the whole PS-Module.

**Comment by LordHepipud** [comment] 2017-07-28 14:51
You're welcome - thank you for testing. I will apply a commit to the 'next' branch with these changed and with a new argument to ignore SSL errors on request, but not on default to keep security.

**Closed as completed** 2017-07-29 08:25 UTC
Labels: bug, enhancement

**Comment by Insurgentes** [comment] 2017-08-02 14:18
Hi,

have been following this thread. I had exactly the same issue as vittel1 so applied the code suggested by LordHepipud  (apart from SSL at the end) but still have some issues:

`Exception calling "createHostInsideIcingaDirector" with "0" argument(s): "Exception calling "createHTTPRequest" with "6"
 argument(s): "Exception calling "GetRequestStream" with "0" argument(s): "The remote name could not be resolved: '<pollername>host'"""`

The strange part there is the url of the poller with 'host' right after it.

Director 1.3.1

Was using the previous 44kb version of the module but really wanted to use the -IcingaServiceUser functionality as the older installer uses windows network service and this blocks uptime/updates check.

I can connect to the director in a browser from the host no probs and I can run the old powershell module without any error messages.

**Comment by LordHepipud** [comment] 2017-08-02 22:40
Can you please review the URL argument?

It has to look like this for example:

```powershell
-DirectorUrl 'https://example.com/icingaweb2/director/'
```

or

```powershell
-DirectorUrl 'https://director.example.com/'
```

Otherwise you will receive the specified error. Maybe adding the last '/' should be done by the module in case it is missing.

**Comment by Insurgentes** [comment] 2017-08-04 10:04
Thank you very much for replying LordHepipud and indeed for all the work you have done on this.  Seems there is a lot more that has changed since the older version I have been using so it's not just the DirectorUrl that I will need to change.  Will get to work on rewriting my script I use with it.

**Comment by Insurgentes** [comment] 2017-08-08 08:24
Sorry to put this here as I have a question but not sure where to post questions related to this (ie so not a bug)  and it's kinda related to the last few posts but I was wondering is there any way to change the service account with the old Powershell Icinga module? The one that was about 44kb.. I am not having so much luck with the new one in my distributed setup and don't have the time to tweak so much at the moment. 

The old version worked fine but the default service account unfortunately is 'network service'.
I tried to grab the service changing code from the new powershell module and place it into the old but then spent a day debugging with no luck.

**Comment by Insurgentes** [comment] 2017-08-08 11:22
Saw your other post to the person having service runas queries and just used:

sc.exe config icinga2 obj="LocalSystem"

at the end of the batch file, so now the service runs with right account after installation.

thanks

**Comment by LordHepipud** [comment] 2017-08-08 21:51
You are welcome :)

**Comment by brettfire** [comment] 2018-12-14 03:31
I had an issue with the latest version of this module grabbing the director version. I found that the script "could not create SSL/TLS secure channel", even though my server has a comodo cert and the cert chain is good. This line allowed the script to work: `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`. Apparently by default, PS uses TLS 1.0, while my server requires at a minimum 1.2. Seems to me like you should add a line such as the former or `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"` to this script. For my deployment, I may just enable TLS 1.0 on my server.

**Comment by LordHepipud** [comment] 2018-12-14 06:42
Thanks for the message. This is already described within the documentation  of the landing page on how to fix the SSL error.

In my oppinion the script shouldn't mess around with which TLS version it's communicating by default. Because I don't want to add hardcoded that TLS 1.0 is supported, while the technology moves on.

Any suggestions?

**Comment by brettfire** [comment] 2018-12-15 08:45
> Thanks for the message. This is already described within the documentation of the landing page on how to fix the SSL error.
> 
> In my oppinion the script shouldn't mess around with which TLS version it's communicating by default. Because I don't want to add hardcoded that TLS 1.0 is supported, while the technology moves on.
> 
> Any suggestions?

Derp, silly me for missing that most obvious piece of info. And I pride myself on reading docs.... 
Your handling of it seems sane. I'll insert that line in my scripts for now (I did enable TLSv1 on my server which is probably less preferable). Carry on!
